/**
 * Rich mock data — used when the backend pipeline isn't running yet.
 * Lets the frontend be fully demoed and iterated on independently.
 */
import type { DashboardSnapshot } from "../types";

export const MOCK_DASHBOARD: DashboardSnapshot = {
  generated_at: new Date().toISOString(),
  top_signals: [
    {
      canonical_name: "HDFC Bank",
      sectors: ["Banking & Finance"],
      mention_count: 312,
      total_reach: 84000,
      composite_score: 0.81,
      frequency_score: 0.9,
      geography_score: 0.95,
      sector_score: 1.0,
      credibility_score: 0.8,
      sentiment_direction: 1,
      sentiment_label: "positive",
      sentiment_plain_label: "Bullish",
      sentiment_magnitude: 0.74,
      signal_strength: "Strong",
      confidence_tier: "High",
      plain_summary:
        "HDFC Bank is seeing strong social signal activity (312 mentions, high confidence). Sentiment is predominantly Bullish across Banking & Finance. This signal is sourced from reddit, google_trends.",
      sample_texts: [
        "HDFC Bank Q1 results beat estimates — margins holding up despite rate environment",
        "HDFC Bank looking like a strong buy at these levels, fundamentals solid",
      ],
      sources: ["reddit", "google_trends"],
      first_seen: new Date(Date.now() - 5 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 12 * 60000).toISOString(),
    },
    {
      canonical_name: "RBI Rate Action",
      sectors: ["Macro / Policy", "Banking & Finance"],
      mention_count: 487,
      total_reach: 142000,
      composite_score: 0.88,
      frequency_score: 0.97,
      geography_score: 0.92,
      sector_score: 1.0,
      credibility_score: 0.85,
      sentiment_direction: -1,
      sentiment_label: "negative",
      sentiment_plain_label: "Bearish",
      sentiment_magnitude: 0.68,
      signal_strength: "Strong",
      confidence_tier: "High",
      plain_summary:
        "RBI Rate Action is the highest-frequency signal in the last 6 hours (487 mentions, high confidence). Sentiment is predominantly Bearish — markets pricing in a hawkish hold. Sourced from reddit, google_trends.",
      sample_texts: [
        "RBI likely to hold rates — no room for cuts given sticky CPI, bad news for rate-sensitives",
        "Another hawkish RBI meeting incoming, bond yields rising",
      ],
      sources: ["reddit", "google_trends"],
      first_seen: new Date(Date.now() - 6 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 5 * 60000).toISOString(),
    },
    {
      canonical_name: "Infosys",
      sectors: ["Information Technology"],
      mention_count: 198,
      total_reach: 52000,
      composite_score: 0.72,
      frequency_score: 0.75,
      geography_score: 0.88,
      sector_score: 0.85,
      credibility_score: 0.75,
      sentiment_direction: 0,
      sentiment_label: "neutral",
      sentiment_plain_label: "Mixed / Neutral",
      sentiment_magnitude: 0.31,
      signal_strength: "Moderate",
      confidence_tier: "High",
      plain_summary:
        "Infosys is seeing moderate activity (198 mentions, high confidence). Sentiment is mixed — guidance cautious but deal wins positive. Sourced from reddit, google_trends.",
      sample_texts: [
        "Infosys deal pipeline improving but FY25 guidance tepid",
        "INFY looking range-bound — wait for clarity on US BFSI demand",
      ],
      sources: ["reddit", "google_trends"],
      first_seen: new Date(Date.now() - 4 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 30 * 60000).toISOString(),
    },
    {
      canonical_name: "Tata Motors",
      sectors: ["Automobile"],
      mention_count: 143,
      total_reach: 38000,
      composite_score: 0.65,
      frequency_score: 0.62,
      geography_score: 0.85,
      sector_score: 0.6,
      credibility_score: 0.7,
      sentiment_direction: 1,
      sentiment_label: "positive",
      sentiment_plain_label: "Bullish",
      sentiment_magnitude: 0.61,
      signal_strength: "Moderate",
      confidence_tier: "High",
      plain_summary:
        "Tata Motors showing bullish sentiment (143 mentions). JLR recovery narrative dominating discussion. Sourced from reddit.",
      sample_texts: ["JLR order book recovery making Tata Motors very interesting at current valuations"],
      sources: ["reddit"],
      first_seen: new Date(Date.now() - 3 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 45 * 60000).toISOString(),
    },
    {
      canonical_name: "IPO Activity",
      sectors: ["General Market"],
      mention_count: 89,
      total_reach: 21000,
      composite_score: 0.48,
      frequency_score: 0.44,
      geography_score: 0.82,
      sector_score: 0.6,
      credibility_score: 0.65,
      sentiment_direction: 1,
      sentiment_label: "positive",
      sentiment_plain_label: "Bullish",
      sentiment_magnitude: 0.55,
      signal_strength: "Emerging",
      confidence_tier: "Medium",
      plain_summary:
        "IPO-related chatter is emerging (89 mentions, medium confidence). Retail sentiment positive around upcoming listings. Sourced from reddit.",
      sample_texts: ["Grey market premium looking spicy on the upcoming SME IPOs"],
      sources: ["reddit"],
      first_seen: new Date(Date.now() - 2 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 90 * 60000).toISOString(),
    },
    {
      canonical_name: "Reliance Industries",
      sectors: ["Energy", "FMCG"],
      mention_count: 211,
      total_reach: 67000,
      composite_score: 0.78,
      frequency_score: 0.82,
      geography_score: 0.91,
      sector_score: 0.85,
      credibility_score: 0.8,
      sentiment_direction: 1,
      sentiment_label: "positive",
      sentiment_plain_label: "Bullish",
      sentiment_magnitude: 0.58,
      signal_strength: "Strong",
      confidence_tier: "High",
      plain_summary:
        "Reliance Industries strong signal (211 mentions). Jio financial services spinoff narrative active. Sourced from reddit, google_trends.",
      sample_texts: ["Reliance Jio Financial Services demerger is the real catalyst to watch"],
      sources: ["reddit", "google_trends"],
      first_seen: new Date(Date.now() - 5 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 20 * 60000).toISOString(),
    },
    {
      canonical_name: "SEBI Regulatory Update",
      sectors: ["Macro / Policy"],
      mention_count: 167,
      total_reach: 45000,
      composite_score: 0.7,
      frequency_score: 0.68,
      geography_score: 0.88,
      sector_score: 1.0,
      credibility_score: 0.85,
      sentiment_direction: -1,
      sentiment_label: "negative",
      sentiment_plain_label: "Bearish",
      sentiment_magnitude: 0.52,
      signal_strength: "Moderate",
      confidence_tier: "High",
      plain_summary:
        "SEBI F&O rule changes generating bearish sentiment (167 mentions). Derivative traders concerned about new lot size norms. Sourced from reddit, google_trends.",
      sample_texts: ["SEBI new F&O rules going to hurt retail participation massively"],
      sources: ["reddit", "google_trends"],
      first_seen: new Date(Date.now() - 6 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 8 * 60000).toISOString(),
    },
    {
      canonical_name: "Sun Pharmaceutical",
      sectors: ["Pharmaceuticals"],
      mention_count: 54,
      total_reach: 12000,
      composite_score: 0.42,
      frequency_score: 0.38,
      geography_score: 0.75,
      sector_score: 0.6,
      credibility_score: 0.7,
      sentiment_direction: 0,
      sentiment_label: "neutral",
      sentiment_plain_label: "Mixed / Neutral",
      sentiment_magnitude: 0.28,
      signal_strength: "Emerging",
      confidence_tier: "Medium",
      plain_summary:
        "Sun Pharma emerging signal (54 mentions, medium confidence). USFDA filing update being discussed. Sourced from reddit.",
      sample_texts: ["Sun Pharma ANDA pipeline stronger than market gives credit for"],
      sources: ["reddit"],
      first_seen: new Date(Date.now() - 1.5 * 3600000).toISOString(),
      last_seen: new Date(Date.now() - 60 * 60000).toISOString(),
    },
  ],
  topic_clusters: [
    {
      topic_id: 0,
      label: "rbi · rate · inflation",
      plain_label: "RBI Rate Action",
      keywords: [["rbi", 0.91], ["rate", 0.88], ["inflation", 0.74], ["repo", 0.71], ["cpi", 0.65]],
      document_count: 487,
      representative_docs: [
        "RBI MPC expected to hold rates amid persistent food inflation — bond markets pricing hawkish hold",
        "Rate sensitive sectors under pressure ahead of RBI decision next week",
      ],
      sectors: ["Macro / Policy", "Banking & Finance"],
      trend_velocity: 1.4,
    },
    {
      topic_id: 1,
      label: "hdfc · bank · results",
      plain_label: "Quarterly Earnings",
      keywords: [["results", 0.85], ["earnings", 0.82], ["profit", 0.78], ["quarter", 0.71], ["beat", 0.65]],
      document_count: 312,
      representative_docs: [
        "Q1 earnings season kicking off — HDFC Bank sets the tone with strong NII growth",
        "IT sector earnings misses weighing on sector sentiment",
      ],
      sectors: ["Banking & Finance", "Information Technology"],
      trend_velocity: 0.9,
    },
    {
      topic_id: 2,
      label: "sebi · fno · rules",
      plain_label: "SEBI Regulatory Update",
      keywords: [["sebi", 0.93], ["fno", 0.87], ["regulation", 0.81], ["lot size", 0.74], ["circular", 0.68]],
      document_count: 167,
      representative_docs: [
        "SEBI's new F&O lot size changes effective next month — brokers bracing for volume drop",
        "SEBI crackdown on options trading — retail traders rattled",
      ],
      sectors: ["Macro / Policy"],
      trend_velocity: 1.8,
    },
    {
      topic_id: 3,
      label: "jlr · tata · ev",
      plain_label: "IT Sector Development",
      keywords: [["jlr", 0.88], ["tata", 0.84], ["ev", 0.79], ["electric", 0.72], ["recovery", 0.61]],
      document_count: 143,
      representative_docs: [
        "Tata Motors JLR recovery making it a top auto pick for H2",
        "EV penetration data strong — Tata leading domestic EV sales again",
      ],
      sectors: ["Automobile"],
      trend_velocity: 0.7,
    },
    {
      topic_id: 4,
      label: "ipo · gmp · listing",
      plain_label: "IPO Activity",
      keywords: [["ipo", 0.92], ["gmp", 0.85], ["listing", 0.80], ["grey market", 0.75], ["allotment", 0.65]],
      document_count: 89,
      representative_docs: [
        "IPO grey market premium signals strong listing gains — retail oversubscription high",
      ],
      sectors: ["General Market"],
      trend_velocity: 0.5,
    },
  ],
  validation: {
    window_label: "Last 6 hours",
    total_documents_processed: 4821,
    total_entities_detected: 8,
    total_topics_found: 5,
    data_freshness_minutes: 12,
    source_breakdown: { reddit: 3940, google_trends: 881 },
    india_mention_pct: 78.4,
    overall_signal_quality: "Strong",
    data_coverage_label: "Comprehensive",
    freshness_label: "Live (< 15 min old)",
    india_coverage_label: "Strongly India-focused (ideal for ET Now use)",
    reliability_summary:
      "This snapshot analysed 4,821 posts and comments collected over the last 6 hours. 8 distinct market entities were detected with measurable sentiment, grouped into 5 narrative themes. Data is 12 minutes old. Overall signal quality is rated STRONG — sufficient for directional inference. India-origin signals account for 78.4% of the dataset.",
    signals_that_preceded_moves: null,
    total_signals_tracked: null,
    historical_accuracy_pct: null,
    accuracy_label: null,
  },
  trending_keywords: [
    { word: "RBI Rate Action", weight: 0.88, mention_count: 487, sector: "Macro / Policy", sentiment: "Bearish", direction: -1, signal_strength: "Strong" },
    { word: "HDFC Bank", weight: 0.81, mention_count: 312, sector: "Banking & Finance", sentiment: "Bullish", direction: 1, signal_strength: "Strong" },
    { word: "Reliance Industries", weight: 0.78, mention_count: 211, sector: "Energy", sentiment: "Bullish", direction: 1, signal_strength: "Strong" },
    { word: "SEBI Regulatory Update", weight: 0.70, mention_count: 167, sector: "Macro / Policy", sentiment: "Bearish", direction: -1, signal_strength: "Moderate" },
    { word: "Infosys", weight: 0.72, mention_count: 198, sector: "IT", sentiment: "Mixed / Neutral", direction: 0, signal_strength: "Moderate" },
    { word: "Tata Motors", weight: 0.65, mention_count: 143, sector: "Automobile", sentiment: "Bullish", direction: 1, signal_strength: "Moderate" },
    { word: "IPO Activity", weight: 0.48, mention_count: 89, sector: "General Market", sentiment: "Bullish", direction: 1, signal_strength: "Emerging" },
    { word: "Sun Pharmaceutical", weight: 0.42, mention_count: 54, sector: "Pharmaceuticals", sentiment: "Mixed / Neutral", direction: 0, signal_strength: "Emerging" },
    { word: "FII Flows", weight: 0.61, mention_count: 122, sector: "Macro / Policy", sentiment: "Bearish", direction: -1, signal_strength: "Moderate" },
    { word: "Nifty 50", weight: 0.75, mention_count: 290, sector: "General Market", sentiment: "Mixed / Neutral", direction: 0, signal_strength: "Strong" },
    { word: "Bajaj Finance", weight: 0.58, mention_count: 98, sector: "Banking & Finance", sentiment: "Bullish", direction: 1, signal_strength: "Moderate" },
    { word: "Coal India", weight: 0.38, mention_count: 44, sector: "Metals & Mining", sentiment: "Bullish", direction: 1, signal_strength: "Emerging" },
  ],
  sector_heatmap: {
    "Banking & Finance": { score: 0.81, direction: 1, mention_count: 432, plain_label: "Net Bullish" },
    "Information Technology": { score: 0.72, direction: 0, mention_count: 198, plain_label: "Mixed" },
    "Macro / Policy": { score: 0.88, direction: -1, mention_count: 654, plain_label: "Net Bearish" },
    "Automobile": { score: 0.65, direction: 1, mention_count: 143, plain_label: "Net Bullish" },
    "Energy": { score: 0.78, direction: 1, mention_count: 211, plain_label: "Net Bullish" },
    "Pharmaceuticals": { score: 0.42, direction: 0, mention_count: 54, plain_label: "Mixed" },
    "FMCG": { score: 0.35, direction: 0, mention_count: 38, plain_label: "Mixed" },
    "General Market": { score: 0.75, direction: 0, mention_count: 412, plain_label: "Mixed" },
  },
};
